version: '3.8'

services:
  db:
    image: postgres
    container_name: antique
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - mylocaldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
   



volumes:
  mylocaldata:
